version: '3.4'

services:
  db:
    image: postgres
  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1