version: '3.4'

services:
  db:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data/
  app:
    build: .
    ports:
      - 8001:8001
    environment:
      PYTHONUNBUFFERED: 1
