# Generated by Django 2.2.5 on 2019-12-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.BigIntegerField(db_index=True)),
                ('end', models.BigIntegerField(db_index=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rossvyaz.Operator')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rossvyaz.Region')),
            ],
        ),
    ]
